apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: bonuspunkte
  name: bonuspunkte
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bonuspunkte-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: bonuspunkte
    spec:
      containers:
        - image: mmlinac/kube-bonuspunkte-service
          name: bonuspunkte
          ports:
            - containerPort: 8080
          resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: bonuspunkte-service
  name: bonuspunkte-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: bonuspunkte-service
  type: LoadBalancer
status:
  loadBalancer: {}