apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: checkout
  name: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      run: checkout
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: checkout
    spec:
      containers:
        - image: mmlinac/kube-checkout-service
          name: checkout
          ports:
            - containerPort: 8080
          resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: checkout
  name: checkout
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: checkout
  type: LoadBalancer
status:
  loadBalancer: {}