apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: versand
  name: versand
spec:
  replicas: 1
  selector:
    matchLabels:
      run: versand
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: versand
    spec:
      containers:
        - image: mmlinac/kube-versand-service
          name: versand
          ports:
            - containerPort: 8080
          resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: versand
  name: versand
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: versand
  type: LoadBalancer
status:
  loadBalancer: {}