apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: zahlung
  name: zahlung
spec:
  replicas: 1
  selector:
    matchLabels:
      run: zahlung
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: zahlung
    spec:
      containers:
        - image: mmlinac/kube-zahlung-service
          name: zahlung
          ports:
            - containerPort: 8080
          resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: zahlung
  name: zahlung
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: zahlung
  type: LoadBalancer
status:
  loadBalancer: {}