apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: usertask
  name: usertask
spec:
  replicas: 1
  selector:
    matchLabels:
      run: usertask
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: usertask
    spec:
      containers:
        - image: mmlinac/kube-usertask
          name: usertask
          ports:
            - containerPort: 8080
          resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: usertask
  name: usertask
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: usertask
  type: LoadBalancer
status:
  loadBalancer: {}