apiVersion: v1
kind: Service
metadata:
  labels:
    run: kafka
  name: kafka-service
spec:
  ports:
    - name: kafka-port
      port: 9092
   #   nodePort: 30092
      targetPort: 9092
      protocol: TCP
  selector:
    run: kafka