apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  name: zookeeper-service
spec:
#  type: NodePort
  ports:
    - name: zookeeper-port
      port: 2181
      protocol: TCP
    #  nodePort: 30181
      targetPort: 2181
  selector:
    run: zookeeper