apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kafka
  template:
    metadata:
      labels:
        run: kafka
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP #minikube ip
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service:2181
            - name: KAFKA_CREATE_TOPICS
              value: checkout1:1:1,checkout2:1:1
          image: wurstmeister/kafka
          imagePullPolicy: IfNotPresent
          name: kafka
          ports:
            - containerPort: 9092