apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    run: kafka
spec:
  type: NodePort
  ports:
    - name: kafka-port
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    run: kafka