apiVersion: v1
kind: Service
metadata:
  labels:
    run: zookeeper-service
  name: zookeeper-service
spec:
  ports:
    - name: zookeeper-port
      port: 2181
      protocol: TCP
      targetPort: 2181
  selector:
    run: zookeeper