apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      run: zookeeper
  template:
    metadata:
      labels:
        run: zookeeper
    spec:
      containers:
        - image: wurstmeister/zookeeper
          imagePullPolicy: IfNotPresent
          name: zookeeper
          ports:
            - containerPort: 2181
